# -*- coding: utf-8 -*-
"""stockprice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_zP3PqY0zXDi_ITC9z0_TaHlJ86Pd4S

# YORW 10-Day Stock Price Prediction using a deep learning Stacked LSTM  
**Goal**: Predict the next 10 closing prices using a 60-day lookback  
**Ticker**: YORW (York Water Company)  
**Model**: 2-layer LSTM + Dropout + Dense(50, ReLU)
**Result**: Sub-$1 average error over 10 days ahead   

---
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Imports & Setup"""

! pip install pandas numpy scikit-learn matplotlib tensorflow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import datetime as dt
import seaborn as sns

"""## 2. Load & Explore Data"""

df=pd.read_csv("YORW.csv")

df.describe()

df.info()

df.isnull().sum()

df.head()

df['Date']=pd.to_datetime(df['Date'])

##Closing prices over time
plt.figure(figsize=(14,7))
plt.plot(df['Date'],df['Close'])
plt.title('Closing prices over time')
plt.xlabel('Date')
plt.ylabel('Close')
plt.show()

##Monthy seasonality of closing prices
df['Month']=df['Date'].dt.month
monthly_avg=df.groupby('Month')['Close'].mean()
plt.figure(figsize=(14,7))
sns.barplot(x=monthly_avg.index,y=monthly_avg.values)
plt.title('Average Closing Price by Month')
plt.xlabel('Month')
plt.ylabel('Average Closing Price')
plt.xticks(range(12), ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.show()

"""## 3. Feature Selection & Scaling"""

df=df.drop(columns=['Date','Adj Close'])
features=['Open','High','Low','Close','Volume']
data=df[features].values

from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaled_data=scaler.fit_transform(df[['Open','High','Low','Close','Volume']])

"""## 4. Create Sequences (60-day input → 10-day output)"""

##Creating sequences
def create_sequences(data,seq_length,pred_length):
  Xs,ys=[],[]
  for i in range(len(data)-seq_length-pred_length+1):
    X=data[i:i+seq_length]
    y=data[i+seq_length:i+seq_length+pred_length,4]
    Xs.append(X)
    ys.append(y)
  return np.array(Xs),np.array(ys)

SEQ_LENGTH=60
PRED_LENGTH=10

X,y=create_sequences(scaled_data,SEQ_LENGTH,PRED_LENGTH)

"""## 5.Chronological split the data"""

##Split the data

train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

print(X_train.shape)

"""## 6. Build Stacked LSTM Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam

def build_lstm_model(input_shape):
  model=Sequential([
      LSTM(units=100,return_sequences=True,input_shape=input_shape),Dropout(0.3),
      LSTM(units=100,return_sequences=False),Dropout(0.3),
      Dense(50,activation='relu'),
      Dense(PRED_LENGTH)

  ])

  model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
  )
  return model

input_shape=(X_train.shape[1],X_train.shape[2])
model=build_lstm_model(input_shape)
model.summary()

"""## 7. Train the model,with callbacks"""

from re import VERBOSE
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint
callbacks = [
    EarlyStopping(patience=10, restore_best_weights=True, monitor='val_loss'),
    ModelCheckpoint("best_10day_perfect_model.keras", save_best_only=True, monitor='val_loss')
]
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=50,
    callbacks=callbacks,
    verbose=1
)

from tensorflow.keras.models import load_model
model=load_model("best_10day_perfect_model.keras")
y_pred_scaled=model.predict(X_test)

"""## 8. Inverse Scaling"""

n_samples = len(y_pred_scaled)
dummy = np.zeros((n_samples * 10, 5))

dummy[:, 3] = y_pred_scaled.flatten()

# Inverse transform
real_prices = scaler.inverse_transform(dummy)[:, 3]

# Reshape back to (samples, 10)
y_pred_real = real_prices.reshape(n_samples, 10)

# do the same for y_test
dummy2 = np.zeros((len(y_test) * 10, 5))
dummy2[:, 3] = y_test.flatten()
y_test_real = scaler.inverse_transform(dummy2)[:, 3].reshape(len(y_test), 10)

##Reconvert back from scaled prices
close_min   = scaler.min_[3]
close_scale = scaler.scale_[3]

y_pred_real = (y_pred_scaled - close_min) / close_scale
y_test_real = (y_test       - close_min) / close_scale

print(y_pred_real[0])

"""## 9. Final Results
Metrics used and their Values     

 MAE   = ~$0.42
     
RMSE = ~$0.68     

"""

from google.colab import files
!jupyter nbconvert --to html *.ipynb
files.download('stockprice.html')

